#!/bin/bash
# Quick script to help deploy the news fix
# This script provides the exact code to paste into Supabase Dashboard

echo "=========================================="
echo "News Fix Deployment Helper"
echo "=========================================="
echo ""
echo "The get-news Edge Function has been fixed with:"
echo "  ✅ CORS support for Vercel domain"
echo "  ✅ Better error handling"
echo "  ✅ Improved logging"
echo ""
echo "To deploy:"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/bfhdtmxmlcfyxjgracbz/functions"
echo "2. Click on 'get-news' function"
echo "3. Click 'Edit' or open the code editor"
echo "4. Copy the entire contents of: supabase/functions/get-news/index.ts"
echo "5. Paste it into the Supabase editor"
echo "6. Click 'Deploy'"
echo ""
echo "OR use Supabase CLI (if installed):"
echo "  supabase functions deploy get-news"
echo ""
echo "=========================================="
echo "Also verify your API key is set:"
echo "  Supabase Dashboard → Edge Functions → Settings → Secrets"
echo "  Make sure 'FINNHUB_API_KEY' exists and is correct"
echo "=========================================="
