/**
 * The universe the Top 100 list ranks.
 *
 * Shared with update-market-caps so the two jobs cannot drift: one keeps these
 * symbols' market caps fresh, the other scores and orders them.
 */
export const TOP_100_SYMBOLS = [
  'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'NVDA', 'META', 'TSLA', 'BRK.B', 'UNH', 'XOM',
  'JNJ', 'JPM', 'V', 'PG', 'MA', 'HD', 'CVX', 'MRK', 'ABBV', 'LLY',
  'PEP', 'KO', 'COST', 'AVGO', 'TMO', 'MCD', 'WMT', 'CSCO', 'ACN', 'ABT',
  'CRM', 'DHR', 'BAC', 'ADBE', 'NKE', 'DIS', 'NFLX', 'CMCSA', 'VZ', 'INTC',
  'PFE', 'TXN', 'PM', 'WFC', 'NEE', 'RTX', 'UPS', 'HON', 'T', 'QCOM',
  'ORCL', 'IBM', 'AMD', 'LOW', 'BMY', 'SPGI', 'UNP', 'CAT', 'GS', 'MS',
  'SBUX', 'BLK', 'DE', 'ELV', 'AMAT', 'ISRG', 'INTU', 'GILD', 'AXP', 'LMT',
  'MDLZ', 'ADI', 'ADP', 'CVS', 'SYK', 'TJX', 'BKNG', 'MMC', 'VRTX', 'REGN',
  'PLD', 'TMUS', 'AMT', 'ZTS', 'SCHW', 'C', 'MO', 'CB', 'SO', 'DUK',
  'CI', 'BDX', 'EOG', 'SLB', 'PNC', 'ICE', 'CL', 'EQIX', 'USB', 'MMM'
];

// Company names mapping
export const COMPANY_NAMES: Record<string, string> = {
  'AAPL': 'Apple Inc.',
  'MSFT': 'Microsoft Corporation',
  'GOOGL': 'Alphabet Inc.',
  'AMZN': 'Amazon.com Inc.',
  'NVDA': 'NVIDIA Corporation',
  'META': 'Meta Platforms Inc.',
  'TSLA': 'Tesla Inc.',
  'BRK.B': 'Berkshire Hathaway Inc.',
  'UNH': 'UnitedHealth Group Inc.',
  'XOM': 'Exxon Mobil Corporation',
  'JNJ': 'Johnson & Johnson',
  'JPM': 'JPMorgan Chase & Co.',
  'V': 'Visa Inc.',
  'PG': 'Procter & Gamble Co.',
  'MA': 'Mastercard Inc.',
  'HD': 'The Home Depot Inc.',
  'CVX': 'Chevron Corporation',
  'MRK': 'Merck & Co. Inc.',
  'ABBV': 'AbbVie Inc.',
  'LLY': 'Eli Lilly and Company',
  'PEP': 'PepsiCo Inc.',
  'KO': 'The Coca-Cola Company',
  'COST': 'Costco Wholesale Corporation',
  'AVGO': 'Broadcom Inc.',
  'TMO': 'Thermo Fisher Scientific Inc.',
  'MCD': "McDonald's Corporation",
  'WMT': 'Walmart Inc.',
  'CSCO': 'Cisco Systems Inc.',
  'ACN': 'Accenture plc',
  'ABT': 'Abbott Laboratories',
  'CRM': 'Salesforce Inc.',
  'DHR': 'Danaher Corporation',
  'BAC': 'Bank of America Corporation',
  'ADBE': 'Adobe Inc.',
  'NKE': 'NIKE Inc.',
  'DIS': 'The Walt Disney Company',
  'NFLX': 'Netflix Inc.',
  'CMCSA': 'Comcast Corporation',
  'VZ': 'Verizon Communications Inc.',
  'INTC': 'Intel Corporation',
  'PFE': 'Pfizer Inc.',
  'TXN': 'Texas Instruments Inc.',
  'PM': 'Philip Morris International Inc.',
  'WFC': 'Wells Fargo & Company',
  'NEE': 'NextEra Energy Inc.',
  'RTX': 'RTX Corporation',
  'UPS': 'United Parcel Service Inc.',
  'HON': 'Honeywell International Inc.',
  'T': 'AT&T Inc.',
  'QCOM': 'QUALCOMM Inc.',
  'ORCL': 'Oracle Corporation',
  'IBM': 'International Business Machines',
  'AMD': 'Advanced Micro Devices Inc.',
  'LOW': "Lowe's Companies Inc.",
  'BMY': 'Bristol-Myers Squibb Company',
  'SPGI': 'S&P Global Inc.',
  'UNP': 'Union Pacific Corporation',
  'CAT': 'Caterpillar Inc.',
  'GS': 'Goldman Sachs Group Inc.',
  'MS': 'Morgan Stanley',
  'SBUX': 'Starbucks Corporation',
  'BLK': 'BlackRock Inc.',
  'DE': 'Deere & Company',
  'ELV': 'Elevance Health Inc.',
  'AMAT': 'Applied Materials Inc.',
  'ISRG': 'Intuitive Surgical Inc.',
  'INTU': 'Intuit Inc.',
  'GILD': 'Gilead Sciences Inc.',
  'AXP': 'American Express Company',
  'LMT': 'Lockheed Martin Corporation',
  'MDLZ': 'Mondelez International Inc.',
  'ADI': 'Analog Devices Inc.',
  'ADP': 'Automatic Data Processing Inc.',
  'CVS': 'CVS Health Corporation',
  'SYK': 'Stryker Corporation',
  'TJX': 'The TJX Companies Inc.',
  'BKNG': 'Booking Holdings Inc.',
  'MMC': 'Marsh & McLennan Companies',
  'VRTX': 'Vertex Pharmaceuticals Inc.',
  'REGN': 'Regeneron Pharmaceuticals Inc.',
  'PLD': 'Prologis Inc.',
  'TMUS': 'T-Mobile US Inc.',
  'AMT': 'American Tower Corporation',
  'ZTS': 'Zoetis Inc.',
  'SCHW': 'Charles Schwab Corporation',
  'C': 'Citigroup Inc.',
  'MO': 'Altria Group Inc.',
  'CB': 'Chubb Limited',
  'SO': 'Southern Company',
  'DUK': 'Duke Energy Corporation',
  'CI': 'The Cigna Group',
  'BDX': 'Becton Dickinson and Company',
  'EOG': 'EOG Resources Inc.',
  'SLB': 'Schlumberger Limited',
  'PNC': 'PNC Financial Services Group',
  'ICE': 'Intercontinental Exchange Inc.',
  'CL': 'Colgate-Palmolive Company',
  'EQIX': 'Equinix Inc.',
  'USB': 'U.S. Bancorp',
  'MMM': '3M Company'
};
