// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables with fallback to hardcoded values for backward compatibility
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://bfhdtmxmlcfyxjgracbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmaGR0bXhtbGNmeXhqZ3JhY2J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTM1NzEsImV4cCI6MjA2ODM4OTU3MX0.4MEGlU9L98n-QGBKTCA8lW8LITzgKpqn5NIbJVlagFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    // Session expires after 1 hour of inactivity (server-side)
    // Client-side timeout is handled by sessionManager.ts
  },
  global: {
    headers: {
      'x-client-info': 'unified-market-app',
    },
  },
  // Realtime configuration for scalability
  realtime: {
    params: {
      eventsPerSecond: 10, // Limit realtime events to prevent flooding
    },
  },
  // DB configuration for better pooling
  db: {
    schema: 'public',
  },
});